"""
apply_asistencia_migration.py
Crea la tabla `matriculas.asistencia_mensual` para el dominio de ANALÍTICA DE
ASISTENCIA (ver steering 10). Idempotente (IF NOT EXISTS), mismo patrón que
apply_renovacion_migration.py / apply_storage_migration.py.

Grano: 1 fila por alumno / mes / establecimiento (igual que el archivo de SIGE).
Fuente: extracto mensual de asistencia (matricula_slepv_2026).

Diseño:
- Llave natural única (id_estudiante, anio_academico, mes_codigo, id_establecimiento)
  -> permite UPSERT idempotente al re-cargar un mes.
- FK a estudiante (ON DELETE CASCADE): si un alumno se borra, su asistencia se va con
  él (coherente con ficha_salud). Guardamos también run_ipe para trazabilidad.
- FK a establecimiento (sin cascada): no se borran establecimientos.
- `segmento`: 'escolar' | 'vtf' | 'excluido' (parvularia/adultos/especial) para que
  el dashboard pueda separar jardines y excluir adultos (decisiones steering 08/10).
- `pct_asist` NUMERIC(5,4) en [0,1]. `rango` y `glosa` como vienen del extracto.

Uso:
    python apply_asistencia_migration.py            # DRY-RUN (muestra el DDL, no aplica)
    python apply_asistencia_migration.py --apply    # crea la tabla/índices
"""
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from database import get_db_connection

DDL_TABLA = """
CREATE TABLE IF NOT EXISTS matriculas.asistencia_mensual (
    id_asistencia       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante       INTEGER NOT NULL
                        REFERENCES matriculas.estudiante(id_estudiante) ON DELETE CASCADE,
    run_ipe             VARCHAR(20) NOT NULL,
    id_establecimiento  INTEGER
                        REFERENCES matriculas.establecimiento(id_establecimiento),
    rbd                 VARCHAR(10),
    anio_academico      INTEGER NOT NULL,
    mes_codigo          INTEGER NOT NULL,
    mes_glosa           VARCHAR(20),
    pct_asist           NUMERIC(5,4) NOT NULL CHECK (pct_asist >= 0 AND pct_asist <= 1),
    rango_asistencia    VARCHAR(20),
    glosa_asistencia    VARCHAR(40),
    segmento            VARCHAR(10) NOT NULL CHECK (segmento IN ('escolar','vtf','excluido')),
    nivel               VARCHAR(60),
    curso               VARCHAR(60),
    cod_ensenanza       INTEGER,
    pie                 VARCHAR(12),
    fecha_carga         TIMESTAMPTZ DEFAULT now()
);
"""

# Llave única natural para UPSERT idempotente de un mes.
DDL_UNIQUE = """
CREATE UNIQUE INDEX IF NOT EXISTS uq_asistencia_alumno_mes
ON matriculas.asistencia_mensual (id_estudiante, anio_academico, mes_codigo, id_establecimiento);
"""

# Índices de consulta para el dashboard/analítica.
DDL_INDICES = [
    "CREATE INDEX IF NOT EXISTS idx_asistencia_estab_anio ON matriculas.asistencia_mensual (id_establecimiento, anio_academico);",
    "CREATE INDEX IF NOT EXISTS idx_asistencia_segmento ON matriculas.asistencia_mensual (segmento, anio_academico);",
    "CREATE INDEX IF NOT EXISTS idx_asistencia_estudiante ON matriculas.asistencia_mensual (id_estudiante);",
]


def migrate(apply: bool):
    print("=" * 60)
    print("MIGRACIÓN: tabla matriculas.asistencia_mensual")
    print("Modo:", "APLICAR" if apply else "DRY-RUN (no escribe)")
    print("=" * 60)
    print("\n-- DDL que se ejecutaría --")
    print(DDL_TABLA)
    print(DDL_UNIQUE)
    for d in DDL_INDICES:
        print(d)

    if not apply:
        print("\nDRY-RUN: no se creó nada. Ejecuta con --apply para crear la tabla.")
        return

    conn = get_db_connection()
    cur = conn.cursor()
    try:
        cur.execute("""SELECT table_name FROM information_schema.tables
                       WHERE table_schema='matriculas' AND table_name='asistencia_mensual'""")
        existe = cur.fetchone()
        cur.execute(DDL_TABLA)
        cur.execute(DDL_UNIQUE)
        for d in DDL_INDICES:
            cur.execute(d)
        conn.commit()
        print("\nTabla 'asistencia_mensual'",
              "ya existía (DDL idempotente, sin cambios destructivos)." if existe
              else "creada correctamente.")
        print("Índices y llave única listos.")
    except Exception as e:
        conn.rollback()
        print(f"Error en la migración: {e}")
        raise
    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    migrate(apply="--apply" in sys.argv)
